hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprland-session.target")
    hl.exec_cmd("noctalia")
    hl.exec_cmd("snappy-switcher --daemon")
    hl.exec_cmd("udiskie --no-tray --automount --notify &")
    hl.exec_cmd("shimejictl mascot summon Capoo")
end)
hl.on("hyprland.shutdown", function()
    os.execute("systemctl --user stop hyprland-session.target && sleep 0.1")
    os.execute("shimejictl stop")
end)
